#!/usr/bin/env bash

# Based on nixpkgs/pkgs/applications/networking/cluster/mesos
#
# I got the artifacts list by doing a build outside nix,
# then going to ~/.m2/repository and running:
#
# find -type f | grep -v '_' | cut -c3- | sort | while read f; do
#   echo "fetch $f"
# done

source $stdenv/setup

fetch() {
  url="http://repo.maven.apache.org/maven2/$1"
  opts='--fail --location --insecure --retry 3 --max-redirs 20 --silent'
  echo "fetching $url"
  mkdir -p $(dirname $out/$1)
  curl $opts "$url" --output "$out/$1"
}

fetch backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
fetch backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar.sha1
fetch backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.pom
fetch backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.pom.sha1
fetch classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom
fetch classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom.sha1
fetch classworlds/classworlds/1.1/classworlds-1.1.pom
fetch classworlds/classworlds/1.1/classworlds-1.1.pom.sha1
fetch com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar
fetch com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar.sha1
fetch com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.pom
fetch com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.pom.sha1
fetch com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.jar
fetch com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.jar.sha1
fetch com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.pom
fetch com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.pom.sha1
fetch com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.jar
fetch com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.jar.sha1
fetch com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.pom
fetch com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.pom.sha1
fetch com/fasterxml/oss-parent/11/oss-parent-11.pom
fetch com/fasterxml/oss-parent/11/oss-parent-11.pom.sha1
fetch com/fasterxml/oss-parent/12/oss-parent-12.pom
fetch com/fasterxml/oss-parent/12/oss-parent-12.pom.sha1
fetch com/github/jsonld-java/jsonld-java/0.5.0/jsonld-java-0.5.0.jar
fetch com/github/jsonld-java/jsonld-java/0.5.0/jsonld-java-0.5.0.jar.sha1
fetch com/github/jsonld-java/jsonld-java/0.5.0/jsonld-java-0.5.0.pom
fetch com/github/jsonld-java/jsonld-java/0.5.0/jsonld-java-0.5.0.pom.sha1
fetch com/github/jsonld-java/jsonld-java-parent/0.5.0/jsonld-java-parent-0.5.0.pom
fetch com/github/jsonld-java/jsonld-java-parent/0.5.0/jsonld-java-parent-0.5.0.pom.sha1
fetch com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
fetch com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar.sha1
fetch com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom
fetch com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom.sha1
fetch com/google/collections/google-collections/1.0/google-collections-1.0.jar
fetch com/google/collections/google-collections/1.0/google-collections-1.0.jar.sha1
fetch com/google/collections/google-collections/1.0/google-collections-1.0.pom
fetch com/google/collections/google-collections/1.0/google-collections-1.0.pom.sha1
fetch com/google/google/1/google-1.pom
fetch com/google/google/1/google-1.pom.sha1
fetch commons-cli/commons-cli/1.0/commons-cli-1.0.jar
fetch commons-cli/commons-cli/1.0/commons-cli-1.0.jar.sha1
fetch commons-cli/commons-cli/1.0/commons-cli-1.0.pom
fetch commons-cli/commons-cli/1.0/commons-cli-1.0.pom.sha1
fetch commons-cli/commons-cli/1.2/commons-cli-1.2.jar
fetch commons-cli/commons-cli/1.2/commons-cli-1.2.jar.sha1
fetch commons-cli/commons-cli/1.2/commons-cli-1.2.pom
fetch commons-cli/commons-cli/1.2/commons-cli-1.2.pom.sha1
fetch commons-codec/commons-codec/1.2/commons-codec-1.2.jar
fetch commons-codec/commons-codec/1.2/commons-codec-1.2.jar.sha1
fetch commons-codec/commons-codec/1.2/commons-codec-1.2.pom
fetch commons-codec/commons-codec/1.2/commons-codec-1.2.pom.sha1
fetch commons-codec/commons-codec/1.6/commons-codec-1.6.jar
fetch commons-codec/commons-codec/1.6/commons-codec-1.6.jar.sha1
fetch commons-codec/commons-codec/1.6/commons-codec-1.6.pom
fetch commons-codec/commons-codec/1.6/commons-codec-1.6.pom.sha1
fetch commons-collections/commons-collections/3.1/commons-collections-3.1.pom
fetch commons-collections/commons-collections/3.1/commons-collections-3.1.pom.sha1
fetch commons-collections/commons-collections/3.2/commons-collections-3.2.jar
fetch commons-collections/commons-collections/3.2/commons-collections-3.2.jar.sha1
fetch commons-collections/commons-collections/3.2/commons-collections-3.2.pom
fetch commons-collections/commons-collections/3.2/commons-collections-3.2.pom.sha1
fetch commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
fetch commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar.sha1
fetch commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom
fetch commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom.sha1
fetch commons-io/commons-io/2.2/commons-io-2.2.jar
fetch commons-io/commons-io/2.2/commons-io-2.2.jar.sha1
fetch commons-io/commons-io/2.2/commons-io-2.2.pom
fetch commons-io/commons-io/2.2/commons-io-2.2.pom.sha1
fetch commons-lang/commons-lang/2.1/commons-lang-2.1.pom
fetch commons-lang/commons-lang/2.1/commons-lang-2.1.pom.sha1
fetch commons-lang/commons-lang/2.4/commons-lang-2.4.jar
fetch commons-lang/commons-lang/2.4/commons-lang-2.4.jar.sha1
fetch commons-lang/commons-lang/2.4/commons-lang-2.4.pom
fetch commons-lang/commons-lang/2.4/commons-lang-2.4.pom.sha1
fetch commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.pom
fetch commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.pom.sha1
fetch commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
fetch commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar.sha1
fetch commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
fetch commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom.sha1
fetch commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
fetch commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar.sha1
fetch commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.pom
fetch commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.pom.sha1
fetch com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar
fetch com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar.sha1
fetch com/thoughtworks/qdox/qdox/1.12/qdox-1.12.pom
fetch com/thoughtworks/qdox/qdox/1.12/qdox-1.12.pom.sha1
fetch doxia/doxia-sink-api/1.0-alpha-4/doxia-sink-api-1.0-alpha-4.pom
fetch doxia/doxia-sink-api/1.0-alpha-4/doxia-sink-api-1.0-alpha-4.pom.sha1
fetch junit/junit/3.8.1/junit-3.8.1.jar
fetch junit/junit/3.8.1/junit-3.8.1.jar.sha1
fetch junit/junit/3.8.1/junit-3.8.1.pom
fetch junit/junit/3.8.1/junit-3.8.1.pom.sha1
fetch junit/junit/3.8.2/junit-3.8.2.jar
fetch junit/junit/3.8.2/junit-3.8.2.jar.sha1
fetch junit/junit/3.8.2/junit-3.8.2.pom
fetch junit/junit/3.8.2/junit-3.8.2.pom.sha1
fetch junit/junit/4.10/junit-4.10.pom
fetch junit/junit/4.10/junit-4.10.pom.sha1
fetch junit/junit/4.11/junit-4.11.jar
fetch junit/junit/4.11/junit-4.11.jar.sha1
fetch junit/junit/4.11/junit-4.11.pom
fetch junit/junit/4.11/junit-4.11.pom.sha1
fetch log4j/log4j/1.2.12/log4j-1.2.12.jar
fetch log4j/log4j/1.2.12/log4j-1.2.12.jar.sha1
fetch log4j/log4j/1.2.12/log4j-1.2.12.pom
fetch log4j/log4j/1.2.12/log4j-1.2.12.pom.sha1
fetch log4j/log4j/1.2.14/log4j-1.2.14.jar
fetch log4j/log4j/1.2.14/log4j-1.2.14.jar.sha1
fetch log4j/log4j/1.2.14/log4j-1.2.14.pom
fetch log4j/log4j/1.2.14/log4j-1.2.14.pom.sha1
fetch log4j/log4j/1.2.17/log4j-1.2.17.jar
fetch log4j/log4j/1.2.17/log4j-1.2.17.jar.sha1
fetch log4j/log4j/1.2.17/log4j-1.2.17.pom
fetch log4j/log4j/1.2.17/log4j-1.2.17.pom.sha1
fetch net/java/dev/stax-utils/stax-utils/20060502/stax-utils-20060502.jar
fetch net/java/dev/stax-utils/stax-utils/20060502/stax-utils-20060502.jar.sha1
fetch net/java/dev/stax-utils/stax-utils/20060502/stax-utils-20060502.pom
fetch net/java/dev/stax-utils/stax-utils/20060502/stax-utils-20060502.pom.sha1
fetch net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
fetch net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar.sha1
fetch net/sf/opencsv/opencsv/2.3/opencsv-2.3.pom
fetch net/sf/opencsv/opencsv/2.3/opencsv-2.3.pom.sha1
fetch net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar
fetch net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar.sha1
fetch net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.pom
fetch net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.pom.sha1
fetch org/apache/apache/10/apache-10.pom
fetch org/apache/apache/10/apache-10.pom.sha1
fetch org/apache/apache/11/apache-11.pom
fetch org/apache/apache/11/apache-11.pom.sha1
fetch org/apache/apache/13/apache-13.pom
fetch org/apache/apache/13/apache-13.pom.sha1
fetch org/apache/apache/14/apache-14.pom
fetch org/apache/apache/14/apache-14.pom.sha1
fetch org/apache/apache/3/apache-3.pom
fetch org/apache/apache/3/apache-3.pom.sha1
fetch org/apache/apache/4/apache-4.pom
fetch org/apache/apache/4/apache-4.pom.sha1
fetch org/apache/apache/5/apache-5.pom
fetch org/apache/apache/5/apache-5.pom.sha1
fetch org/apache/apache/6/apache-6.pom
fetch org/apache/apache/6/apache-6.pom.sha1
fetch org/apache/apache/7/apache-7.pom
fetch org/apache/apache/7/apache-7.pom.sha1
fetch org/apache/apache/9/apache-9.pom
fetch org/apache/apache/9/apache-9.pom.sha1
fetch org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
fetch org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar.sha1
fetch org/apache/commons/commons-compress/1.5/commons-compress-1.5.pom
fetch org/apache/commons/commons-compress/1.5/commons-compress-1.5.pom.sha1
fetch org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
fetch org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar.sha1
fetch org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
fetch org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom.sha1
fetch org/apache/commons/commons-parent/11/commons-parent-11.pom
fetch org/apache/commons/commons-parent/11/commons-parent-11.pom.sha1
fetch org/apache/commons/commons-parent/22/commons-parent-22.pom
fetch org/apache/commons/commons-parent/22/commons-parent-22.pom.sha1
fetch org/apache/commons/commons-parent/24/commons-parent-24.pom
fetch org/apache/commons/commons-parent/24/commons-parent-24.pom.sha1
fetch org/apache/commons/commons-parent/28/commons-parent-28.pom
fetch org/apache/commons/commons-parent/28/commons-parent-28.pom.sha1
fetch org/apache/commons/commons-parent/5/commons-parent-5.pom
fetch org/apache/commons/commons-parent/5/commons-parent-5.pom.sha1
fetch org/apache/commons/commons-parent/9/commons-parent-9.pom
fetch org/apache/commons/commons-parent/9/commons-parent-9.pom.sha1
fetch org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar
fetch org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar.sha1
fetch org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.pom
fetch org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.pom.sha1
fetch org/apache/httpcomponents/httpclient-cache/4.2.6/httpclient-cache-4.2.6.jar
fetch org/apache/httpcomponents/httpclient-cache/4.2.6/httpclient-cache-4.2.6.jar.sha1
fetch org/apache/httpcomponents/httpclient-cache/4.2.6/httpclient-cache-4.2.6.pom
fetch org/apache/httpcomponents/httpclient-cache/4.2.6/httpclient-cache-4.2.6.pom.sha1
fetch org/apache/httpcomponents/httpcomponents-client/4.2.6/httpcomponents-client-4.2.6.pom
fetch org/apache/httpcomponents/httpcomponents-client/4.2.6/httpcomponents-client-4.2.6.pom.sha1
fetch org/apache/httpcomponents/httpcomponents-core/4.2.5/httpcomponents-core-4.2.5.pom
fetch org/apache/httpcomponents/httpcomponents-core/4.2.5/httpcomponents-core-4.2.5.pom.sha1
fetch org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar
fetch org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar.sha1
fetch org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.pom
fetch org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.pom.sha1
fetch org/apache/httpcomponents/project/7/project-7.pom
fetch org/apache/httpcomponents/project/7/project-7.pom.sha1
fetch org/apache/jena/jena-arq/2.12.0/jena-arq-2.12.0.jar
fetch org/apache/jena/jena-arq/2.12.0/jena-arq-2.12.0.jar.sha1
fetch org/apache/jena/jena-arq/2.12.0/jena-arq-2.12.0.pom
fetch org/apache/jena/jena-arq/2.12.0/jena-arq-2.12.0.pom.sha1
fetch org/apache/jena/jena-core/2.12.0/jena-core-2.12.0.jar
fetch org/apache/jena/jena-core/2.12.0/jena-core-2.12.0.jar.sha1
fetch org/apache/jena/jena-core/2.12.0/jena-core-2.12.0.pom
fetch org/apache/jena/jena-core/2.12.0/jena-core-2.12.0.pom.sha1
fetch org/apache/jena/jena-iri/1.1.0/jena-iri-1.1.0.jar
fetch org/apache/jena/jena-iri/1.1.0/jena-iri-1.1.0.jar.sha1
fetch org/apache/jena/jena-iri/1.1.0/jena-iri-1.1.0.pom
fetch org/apache/jena/jena-iri/1.1.0/jena-iri-1.1.0.pom.sha1
fetch org/apache/jena/jena-parent/10/jena-parent-10.pom
fetch org/apache/jena/jena-parent/10/jena-parent-10.pom.sha1
fetch org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom
fetch org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom.sha1
fetch org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom
fetch org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom
fetch org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom.sha1
fetch org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
fetch org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom
fetch org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-decoration-model/1.0/doxia-decoration-model-1.0.jar
fetch org/apache/maven/doxia/doxia-decoration-model/1.0/doxia-decoration-model-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-decoration-model/1.0/doxia-decoration-model-1.0.pom
fetch org/apache/maven/doxia/doxia-decoration-model/1.0/doxia-decoration-model-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom
fetch org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom.sha1
fetch org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar
fetch org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom
fetch org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar
fetch org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom
fetch org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom
fetch org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar
fetch org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom
fetch org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar
fetch org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom
fetch org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar
fetch org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar.sha1
fetch org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom
fetch org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom.sha1
fetch org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
fetch org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom
fetch org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom
fetch org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom.sha1
fetch org/apache/maven/doxia/doxia-site-renderer/1.0/doxia-site-renderer-1.0.jar
fetch org/apache/maven/doxia/doxia-site-renderer/1.0/doxia-site-renderer-1.0.jar.sha1
fetch org/apache/maven/doxia/doxia-site-renderer/1.0/doxia-site-renderer-1.0.pom
fetch org/apache/maven/doxia/doxia-site-renderer/1.0/doxia-site-renderer-1.0.pom.sha1
fetch org/apache/maven/doxia/doxia-sitetools/1.0/doxia-sitetools-1.0.pom
fetch org/apache/maven/doxia/doxia-sitetools/1.0/doxia-sitetools-1.0.pom.sha1
fetch org/apache/maven/maven/2.0.10/maven-2.0.10.pom
fetch org/apache/maven/maven/2.0.10/maven-2.0.10.pom.sha1
fetch org/apache/maven/maven/2.0.2/maven-2.0.2.pom
fetch org/apache/maven/maven/2.0.2/maven-2.0.2.pom.sha1
fetch org/apache/maven/maven/2.0.4/maven-2.0.4.pom
fetch org/apache/maven/maven/2.0.4/maven-2.0.4.pom.sha1
fetch org/apache/maven/maven/2.0.6/maven-2.0.6.pom
fetch org/apache/maven/maven/2.0.6/maven-2.0.6.pom.sha1
fetch org/apache/maven/maven/2.0.8/maven-2.0.8.pom
fetch org/apache/maven/maven/2.0.8/maven-2.0.8.pom.sha1
fetch org/apache/maven/maven/2.0.9/maven-2.0.9.pom
fetch org/apache/maven/maven/2.0.9/maven-2.0.9.pom.sha1
fetch org/apache/maven/maven/2.0/maven-2.0.pom
fetch org/apache/maven/maven/2.0/maven-2.0.pom.sha1
fetch org/apache/maven/maven/2.2.1/maven-2.2.1.pom
fetch org/apache/maven/maven/2.2.1/maven-2.2.1.pom.sha1
fetch org/apache/maven/maven-archiver/2.4/maven-archiver-2.4.jar
fetch org/apache/maven/maven-archiver/2.4/maven-archiver-2.4.jar.sha1
fetch org/apache/maven/maven-archiver/2.4/maven-archiver-2.4.pom
fetch org/apache/maven/maven-archiver/2.4/maven-archiver-2.4.pom.sha1
fetch org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
fetch org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar.sha1
fetch org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom
fetch org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom.sha1
fetch org/apache/maven/maven-artifact/2.0.10/maven-artifact-2.0.10.pom
fetch org/apache/maven/maven-artifact/2.0.10/maven-artifact-2.0.10.pom.sha1
fetch org/apache/maven/maven-artifact/2.0.2/maven-artifact-2.0.2.pom
fetch org/apache/maven/maven-artifact/2.0.2/maven-artifact-2.0.2.pom.sha1
fetch org/apache/maven/maven-artifact/2.0.4/maven-artifact-2.0.4.pom
fetch org/apache/maven/maven-artifact/2.0.4/maven-artifact-2.0.4.pom.sha1
fetch org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.pom
fetch org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.pom.sha1
fetch org/apache/maven/maven-artifact/2.0.8/maven-artifact-2.0.8.pom
fetch org/apache/maven/maven-artifact/2.0.8/maven-artifact-2.0.8.pom.sha1
fetch org/apache/maven/maven-artifact/2.0.9/maven-artifact-2.0.9.pom
fetch org/apache/maven/maven-artifact/2.0.9/maven-artifact-2.0.9.pom.sha1
fetch org/apache/maven/maven-artifact/2.0/maven-artifact-2.0.pom
fetch org/apache/maven/maven-artifact/2.0/maven-artifact-2.0.pom.sha1
fetch org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.pom
fetch org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0.10/maven-artifact-manager-2.0.10.pom
fetch org/apache/maven/maven-artifact-manager/2.0.10/maven-artifact-manager-2.0.10.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0.2/maven-artifact-manager-2.0.2.pom
fetch org/apache/maven/maven-artifact-manager/2.0.2/maven-artifact-manager-2.0.2.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0.4/maven-artifact-manager-2.0.4.pom
fetch org/apache/maven/maven-artifact-manager/2.0.4/maven-artifact-manager-2.0.4.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.pom
fetch org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0.8/maven-artifact-manager-2.0.8.pom
fetch org/apache/maven/maven-artifact-manager/2.0.8/maven-artifact-manager-2.0.8.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.pom
fetch org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.0/maven-artifact-manager-2.0.pom
fetch org/apache/maven/maven-artifact-manager/2.0/maven-artifact-manager-2.0.pom.sha1
fetch org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.pom
fetch org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.pom.sha1
fetch org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.pom
fetch org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.pom.sha1
fetch org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom
fetch org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom.sha1
fetch org/apache/maven/maven-core/2.0/maven-core-2.0.pom
fetch org/apache/maven/maven-core/2.0/maven-core-2.0.pom.sha1
fetch org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom
fetch org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom.sha1
fetch org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.pom
fetch org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.pom.sha1
fetch org/apache/maven/maven-error-diagnostics/2.0.9/maven-error-diagnostics-2.0.9.pom
fetch org/apache/maven/maven-error-diagnostics/2.0.9/maven-error-diagnostics-2.0.9.pom.sha1
fetch org/apache/maven/maven-error-diagnostics/2.0/maven-error-diagnostics-2.0.pom
fetch org/apache/maven/maven-error-diagnostics/2.0/maven-error-diagnostics-2.0.pom.sha1
fetch org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.pom
fetch org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.pom.sha1
fetch org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.pom
fetch org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.pom.sha1
fetch org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.pom
fetch org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.pom.sha1
fetch org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom
fetch org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom.sha1
fetch org/apache/maven/maven-model/2.0.8/maven-model-2.0.8.pom
fetch org/apache/maven/maven-model/2.0.8/maven-model-2.0.8.pom.sha1
fetch org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom
fetch org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom.sha1
fetch org/apache/maven/maven-model/2.0/maven-model-2.0.pom
fetch org/apache/maven/maven-model/2.0/maven-model-2.0.pom.sha1
fetch org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom
fetch org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom.sha1
fetch org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.pom
fetch org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.pom.sha1
fetch org/apache/maven/maven-monitor/2.0.9/maven-monitor-2.0.9.pom
fetch org/apache/maven/maven-monitor/2.0.9/maven-monitor-2.0.9.pom.sha1
fetch org/apache/maven/maven-monitor/2.0/maven-monitor-2.0.pom
fetch org/apache/maven/maven-monitor/2.0/maven-monitor-2.0.pom.sha1
fetch org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.pom
fetch org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.pom.sha1
fetch org/apache/maven/maven-parent/10/maven-parent-10.pom
fetch org/apache/maven/maven-parent/10/maven-parent-10.pom.sha1
fetch org/apache/maven/maven-parent/11/maven-parent-11.pom
fetch org/apache/maven/maven-parent/11/maven-parent-11.pom.sha1
fetch org/apache/maven/maven-parent/13/maven-parent-13.pom
fetch org/apache/maven/maven-parent/13/maven-parent-13.pom.sha1
fetch org/apache/maven/maven-parent/15/maven-parent-15.pom
fetch org/apache/maven/maven-parent/15/maven-parent-15.pom.sha1
fetch org/apache/maven/maven-parent/16/maven-parent-16.pom
fetch org/apache/maven/maven-parent/16/maven-parent-16.pom.sha1
fetch org/apache/maven/maven-parent/21/maven-parent-21.pom
fetch org/apache/maven/maven-parent/21/maven-parent-21.pom.sha1
fetch org/apache/maven/maven-parent/22/maven-parent-22.pom
fetch org/apache/maven/maven-parent/22/maven-parent-22.pom.sha1
fetch org/apache/maven/maven-parent/23/maven-parent-23.pom
fetch org/apache/maven/maven-parent/23/maven-parent-23.pom.sha1
fetch org/apache/maven/maven-parent/24/maven-parent-24.pom
fetch org/apache/maven/maven-parent/24/maven-parent-24.pom.sha1
fetch org/apache/maven/maven-parent/4/maven-parent-4.pom
fetch org/apache/maven/maven-parent/4/maven-parent-4.pom.sha1
fetch org/apache/maven/maven-parent/5/maven-parent-5.pom
fetch org/apache/maven/maven-parent/5/maven-parent-5.pom.sha1
fetch org/apache/maven/maven-parent/6/maven-parent-6.pom
fetch org/apache/maven/maven-parent/6/maven-parent-6.pom.sha1
fetch org/apache/maven/maven-parent/7/maven-parent-7.pom
fetch org/apache/maven/maven-parent/7/maven-parent-7.pom.sha1
fetch org/apache/maven/maven-parent/8/maven-parent-8.pom
fetch org/apache/maven/maven-parent/8/maven-parent-8.pom.sha1
fetch org/apache/maven/maven-parent/9/maven-parent-9.pom
fetch org/apache/maven/maven-parent/9/maven-parent-9.pom.sha1
fetch org/apache/maven/maven-plugin-api/2.0.4/maven-plugin-api-2.0.4.pom
fetch org/apache/maven/maven-plugin-api/2.0.4/maven-plugin-api-2.0.4.pom.sha1
fetch org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom
fetch org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom.sha1
fetch org/apache/maven/maven-plugin-api/2.0.8/maven-plugin-api-2.0.8.pom
fetch org/apache/maven/maven-plugin-api/2.0.8/maven-plugin-api-2.0.8.pom.sha1
fetch org/apache/maven/maven-plugin-api/2.0.9/maven-plugin-api-2.0.9.pom
fetch org/apache/maven/maven-plugin-api/2.0.9/maven-plugin-api-2.0.9.pom.sha1
fetch org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.pom
fetch org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.pom.sha1
fetch org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.pom
fetch org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.pom.sha1
fetch org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.pom
fetch org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.pom.sha1
fetch org/apache/maven/maven-plugin-descriptor/2.0.9/maven-plugin-descriptor-2.0.9.pom
fetch org/apache/maven/maven-plugin-descriptor/2.0.9/maven-plugin-descriptor-2.0.9.pom.sha1
fetch org/apache/maven/maven-plugin-descriptor/2.0/maven-plugin-descriptor-2.0.pom
fetch org/apache/maven/maven-plugin-descriptor/2.0/maven-plugin-descriptor-2.0.pom.sha1
fetch org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.pom
fetch org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.pom.sha1
fetch org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.pom
fetch org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.pom.sha1
fetch org/apache/maven/maven-plugin-parameter-documenter/2.0.9/maven-plugin-parameter-documenter-2.0.9.pom
fetch org/apache/maven/maven-plugin-parameter-documenter/2.0.9/maven-plugin-parameter-documenter-2.0.9.pom.sha1
fetch org/apache/maven/maven-plugin-parameter-documenter/2.0/maven-plugin-parameter-documenter-2.0.pom
fetch org/apache/maven/maven-plugin-parameter-documenter/2.0/maven-plugin-parameter-documenter-2.0.pom.sha1
fetch org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.pom
fetch org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.pom.sha1
fetch org/apache/maven/maven-plugin-registry/2.0.10/maven-plugin-registry-2.0.10.pom
fetch org/apache/maven/maven-plugin-registry/2.0.10/maven-plugin-registry-2.0.10.pom.sha1
fetch org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.pom
fetch org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.pom.sha1
fetch org/apache/maven/maven-plugin-registry/2.0.8/maven-plugin-registry-2.0.8.pom
fetch org/apache/maven/maven-plugin-registry/2.0.8/maven-plugin-registry-2.0.8.pom.sha1
fetch org/apache/maven/maven-plugin-registry/2.0.9/maven-plugin-registry-2.0.9.pom
fetch org/apache/maven/maven-plugin-registry/2.0.9/maven-plugin-registry-2.0.9.pom.sha1
fetch org/apache/maven/maven-plugin-registry/2.0/maven-plugin-registry-2.0.pom
fetch org/apache/maven/maven-plugin-registry/2.0/maven-plugin-registry-2.0.pom.sha1
fetch org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.pom
fetch org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.pom.sha1
fetch org/apache/maven/maven-profile/2.0.10/maven-profile-2.0.10.pom
fetch org/apache/maven/maven-profile/2.0.10/maven-profile-2.0.10.pom.sha1
fetch org/apache/maven/maven-profile/2.0.4/maven-profile-2.0.4.pom
fetch org/apache/maven/maven-profile/2.0.4/maven-profile-2.0.4.pom.sha1
fetch org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.pom
fetch org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.pom.sha1
fetch org/apache/maven/maven-profile/2.0.8/maven-profile-2.0.8.pom
fetch org/apache/maven/maven-profile/2.0.8/maven-profile-2.0.8.pom.sha1
fetch org/apache/maven/maven-profile/2.0.9/maven-profile-2.0.9.pom
fetch org/apache/maven/maven-profile/2.0.9/maven-profile-2.0.9.pom.sha1
fetch org/apache/maven/maven-profile/2.0/maven-profile-2.0.pom
fetch org/apache/maven/maven-profile/2.0/maven-profile-2.0.pom.sha1
fetch org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.pom
fetch org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.pom.sha1
fetch org/apache/maven/maven-project/2.0.10/maven-project-2.0.10.pom
fetch org/apache/maven/maven-project/2.0.10/maven-project-2.0.10.pom.sha1
fetch org/apache/maven/maven-project/2.0.4/maven-project-2.0.4.pom
fetch org/apache/maven/maven-project/2.0.4/maven-project-2.0.4.pom.sha1
fetch org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.pom
fetch org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.pom.sha1
fetch org/apache/maven/maven-project/2.0.8/maven-project-2.0.8.pom
fetch org/apache/maven/maven-project/2.0.8/maven-project-2.0.8.pom.sha1
fetch org/apache/maven/maven-project/2.0.9/maven-project-2.0.9.pom
fetch org/apache/maven/maven-project/2.0.9/maven-project-2.0.9.pom.sha1
fetch org/apache/maven/maven-project/2.0/maven-project-2.0.pom
fetch org/apache/maven/maven-project/2.0/maven-project-2.0.pom.sha1
fetch org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.pom
fetch org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0.10/maven-repository-metadata-2.0.10.pom
fetch org/apache/maven/maven-repository-metadata/2.0.10/maven-repository-metadata-2.0.10.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0.2/maven-repository-metadata-2.0.2.pom
fetch org/apache/maven/maven-repository-metadata/2.0.2/maven-repository-metadata-2.0.2.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0.4/maven-repository-metadata-2.0.4.pom
fetch org/apache/maven/maven-repository-metadata/2.0.4/maven-repository-metadata-2.0.4.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom
fetch org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.pom
fetch org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom
fetch org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.0/maven-repository-metadata-2.0.pom
fetch org/apache/maven/maven-repository-metadata/2.0/maven-repository-metadata-2.0.pom.sha1
fetch org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.pom
fetch org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.pom.sha1
fetch org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.pom
fetch org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.pom.sha1
fetch org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.pom
fetch org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.pom.sha1
fetch org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom
fetch org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom.sha1
fetch org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.pom
fetch org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.pom.sha1
fetch org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom
fetch org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom.sha1
fetch org/apache/maven/maven-settings/2.0/maven-settings-2.0.pom
fetch org/apache/maven/maven-settings/2.0/maven-settings-2.0.pom.sha1
fetch org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom
fetch org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom.sha1
fetch org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.pom
fetch org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.pom.sha1
fetch org/apache/maven/maven-toolchain/2.0.9/maven-toolchain-2.0.9.pom
fetch org/apache/maven/maven-toolchain/2.0.9/maven-toolchain-2.0.9.pom.sha1
fetch org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.pom
fetch org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.pom.sha1
fetch org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
fetch org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar.sha1
fetch org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
fetch org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom.sha1
fetch org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar
fetch org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar.sha1
fetch org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom
fetch org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom.sha1
fetch org/apache/maven/plugins/maven-jar-plugin/2.5/maven-jar-plugin-2.5.jar
fetch org/apache/maven/plugins/maven-jar-plugin/2.5/maven-jar-plugin-2.5.jar.sha1
fetch org/apache/maven/plugins/maven-jar-plugin/2.5/maven-jar-plugin-2.5.pom
fetch org/apache/maven/plugins/maven-jar-plugin/2.5/maven-jar-plugin-2.5.pom.sha1
fetch org/apache/maven/plugins/maven-javadoc-plugin/2.9/maven-javadoc-plugin-2.9.jar
fetch org/apache/maven/plugins/maven-javadoc-plugin/2.9/maven-javadoc-plugin-2.9.jar.sha1
fetch org/apache/maven/plugins/maven-javadoc-plugin/2.9/maven-javadoc-plugin-2.9.pom
fetch org/apache/maven/plugins/maven-javadoc-plugin/2.9/maven-javadoc-plugin-2.9.pom.sha1
fetch org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
fetch org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom.sha1
fetch org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
fetch org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom.sha1
fetch org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom
fetch org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom.sha1
fetch org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom
fetch org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom.sha1
fetch org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
fetch org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar.sha1
fetch org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
fetch org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom.sha1
fetch org/apache/maven/plugins/maven-source-plugin/2.2.1/maven-source-plugin-2.2.1.jar
fetch org/apache/maven/plugins/maven-source-plugin/2.2.1/maven-source-plugin-2.2.1.jar.sha1
fetch org/apache/maven/plugins/maven-source-plugin/2.2.1/maven-source-plugin-2.2.1.pom
fetch org/apache/maven/plugins/maven-source-plugin/2.2.1/maven-source-plugin-2.2.1.pom.sha1
fetch org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar
fetch org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar.sha1
fetch org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
fetch org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom.sha1
fetch org/apache/maven/plugin-tools/maven-plugin-annotations/3.1/maven-plugin-annotations-3.1.jar
fetch org/apache/maven/plugin-tools/maven-plugin-annotations/3.1/maven-plugin-annotations-3.1.jar.sha1
fetch org/apache/maven/plugin-tools/maven-plugin-annotations/3.1/maven-plugin-annotations-3.1.pom
fetch org/apache/maven/plugin-tools/maven-plugin-annotations/3.1/maven-plugin-annotations-3.1.pom.sha1
fetch org/apache/maven/plugin-tools/maven-plugin-tools/3.1/maven-plugin-tools-3.1.pom
fetch org/apache/maven/plugin-tools/maven-plugin-tools/3.1/maven-plugin-tools-3.1.pom.sha1
fetch org/apache/maven/reporting/maven-reporting/2.0.6/maven-reporting-2.0.6.pom
fetch org/apache/maven/reporting/maven-reporting/2.0.6/maven-reporting-2.0.6.pom.sha1
fetch org/apache/maven/reporting/maven-reporting/2.0.9/maven-reporting-2.0.9.pom
fetch org/apache/maven/reporting/maven-reporting/2.0.9/maven-reporting-2.0.9.pom.sha1
fetch org/apache/maven/reporting/maven-reporting/2.0/maven-reporting-2.0.pom
fetch org/apache/maven/reporting/maven-reporting/2.0/maven-reporting-2.0.pom.sha1
fetch org/apache/maven/reporting/maven-reporting/2.2.1/maven-reporting-2.2.1.pom
fetch org/apache/maven/reporting/maven-reporting/2.2.1/maven-reporting-2.2.1.pom.sha1
fetch org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar
fetch org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar.sha1
fetch org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.pom
fetch org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.pom.sha1
fetch org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar
fetch org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar.sha1
fetch org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.pom
fetch org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.pom.sha1
fetch org/apache/maven/reporting/maven-reporting-api/2.0/maven-reporting-api-2.0.pom
fetch org/apache/maven/reporting/maven-reporting-api/2.0/maven-reporting-api-2.0.pom.sha1
fetch org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.pom
fetch org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.pom.sha1
fetch org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
fetch org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar.sha1
fetch org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom
fetch org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom.sha1
fetch org/apache/maven/shared/file-management/1.1/file-management-1.1.jar
fetch org/apache/maven/shared/file-management/1.1/file-management-1.1.jar.sha1
fetch org/apache/maven/shared/file-management/1.1/file-management-1.1.pom
fetch org/apache/maven/shared/file-management/1.1/file-management-1.1.pom.sha1
fetch org/apache/maven/shared/maven-common-artifact-filters/1.0-alpha-1/maven-common-artifact-filters-1.0-alpha-1.pom
fetch org/apache/maven/shared/maven-common-artifact-filters/1.0-alpha-1/maven-common-artifact-filters-1.0-alpha-1.pom.sha1
fetch org/apache/maven/shared/maven-common-artifact-filters/1.1/maven-common-artifact-filters-1.1.jar
fetch org/apache/maven/shared/maven-common-artifact-filters/1.1/maven-common-artifact-filters-1.1.jar.sha1
fetch org/apache/maven/shared/maven-common-artifact-filters/1.1/maven-common-artifact-filters-1.1.pom
fetch org/apache/maven/shared/maven-common-artifact-filters/1.1/maven-common-artifact-filters-1.1.pom.sha1
fetch org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.jar
fetch org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.jar.sha1
fetch org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.pom
fetch org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.pom.sha1
fetch org/apache/maven/shared/maven-filtering/1.0-beta-2/maven-filtering-1.0-beta-2.jar
fetch org/apache/maven/shared/maven-filtering/1.0-beta-2/maven-filtering-1.0-beta-2.jar.sha1
fetch org/apache/maven/shared/maven-filtering/1.0-beta-2/maven-filtering-1.0-beta-2.pom
fetch org/apache/maven/shared/maven-filtering/1.0-beta-2/maven-filtering-1.0-beta-2.pom.sha1
fetch org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar
fetch org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar.sha1
fetch org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom
fetch org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom.sha1
fetch org/apache/maven/shared/maven-invoker/2.0.9/maven-invoker-2.0.9.jar
fetch org/apache/maven/shared/maven-invoker/2.0.9/maven-invoker-2.0.9.jar.sha1
fetch org/apache/maven/shared/maven-invoker/2.0.9/maven-invoker-2.0.9.pom
fetch org/apache/maven/shared/maven-invoker/2.0.9/maven-invoker-2.0.9.pom.sha1
fetch org/apache/maven/shared/maven-plugin-testing-harness/1.1/maven-plugin-testing-harness-1.1.jar
fetch org/apache/maven/shared/maven-plugin-testing-harness/1.1/maven-plugin-testing-harness-1.1.jar.sha1
fetch org/apache/maven/shared/maven-plugin-testing-harness/1.1/maven-plugin-testing-harness-1.1.pom
fetch org/apache/maven/shared/maven-plugin-testing-harness/1.1/maven-plugin-testing-harness-1.1.pom.sha1
fetch org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.jar
fetch org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.jar.sha1
fetch org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.pom
fetch org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/10/maven-shared-components-10.pom
fetch org/apache/maven/shared/maven-shared-components/10/maven-shared-components-10.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom
fetch org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom
fetch org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/17/maven-shared-components-17.pom
fetch org/apache/maven/shared/maven-shared-components/17/maven-shared-components-17.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/18/maven-shared-components-18.pom
fetch org/apache/maven/shared/maven-shared-components/18/maven-shared-components-18.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/19/maven-shared-components-19.pom
fetch org/apache/maven/shared/maven-shared-components/19/maven-shared-components-19.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/4/maven-shared-components-4.pom
fetch org/apache/maven/shared/maven-shared-components/4/maven-shared-components-4.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/6/maven-shared-components-6.pom
fetch org/apache/maven/shared/maven-shared-components/6/maven-shared-components-6.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/7/maven-shared-components-7.pom
fetch org/apache/maven/shared/maven-shared-components/7/maven-shared-components-7.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/8/maven-shared-components-8.pom
fetch org/apache/maven/shared/maven-shared-components/8/maven-shared-components-8.pom.sha1
fetch org/apache/maven/shared/maven-shared-components/9/maven-shared-components-9.pom
fetch org/apache/maven/shared/maven-shared-components/9/maven-shared-components-9.pom.sha1
fetch org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar
fetch org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar.sha1
fetch org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.pom
fetch org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.pom.sha1
fetch org/apache/maven/shared/maven-shared-io/1.0/maven-shared-io-1.0.pom
fetch org/apache/maven/shared/maven-shared-io/1.0/maven-shared-io-1.0.pom.sha1
fetch org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.jar
fetch org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.jar.sha1
fetch org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.pom
fetch org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.pom.sha1
fetch org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.jar
fetch org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.jar.sha1
fetch org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.pom
fetch org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.pom.sha1
fetch org/apache/maven/surefire/maven-surefire-common/2.12.4/maven-surefire-common-2.12.4.jar
fetch org/apache/maven/surefire/maven-surefire-common/2.12.4/maven-surefire-common-2.12.4.jar.sha1
fetch org/apache/maven/surefire/maven-surefire-common/2.12.4/maven-surefire-common-2.12.4.pom
fetch org/apache/maven/surefire/maven-surefire-common/2.12.4/maven-surefire-common-2.12.4.pom.sha1
fetch org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom
fetch org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom.sha1
fetch org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.jar
fetch org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.jar.sha1
fetch org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.pom
fetch org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.pom.sha1
fetch org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.jar
fetch org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.jar.sha1
fetch org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.pom
fetch org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.pom.sha1
fetch org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar
fetch org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar.sha1
fetch org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.pom
fetch org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.pom.sha1
fetch org/apache/maven/surefire/surefire-providers/2.12.4/surefire-providers-2.12.4.pom
fetch org/apache/maven/surefire/surefire-providers/2.12.4/surefire-providers-2.12.4.pom.sha1
fetch org/apache/maven/wagon/wagon/1.0-alpha-6/wagon-1.0-alpha-6.pom
fetch org/apache/maven/wagon/wagon/1.0-alpha-6/wagon-1.0-alpha-6.pom.sha1
fetch org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.pom
fetch org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.pom.sha1
fetch org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6/wagon-provider-api-1.0-alpha-6.pom
fetch org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6/wagon-provider-api-1.0-alpha-6.pom.sha1
fetch org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.pom
fetch org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.pom.sha1
fetch org/apache/velocity/velocity/1.5/velocity-1.5.jar
fetch org/apache/velocity/velocity/1.5/velocity-1.5.jar.sha1
fetch org/apache/velocity/velocity/1.5/velocity-1.5.pom
fetch org/apache/velocity/velocity/1.5/velocity-1.5.pom.sha1
fetch org/apache/xbean/xbean/3.4/xbean-3.4.pom
fetch org/apache/xbean/xbean/3.4/xbean-3.4.pom.sha1
fetch org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
fetch org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar.sha1
fetch org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.pom
fetch org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.pom.sha1
fetch org/codehaus/codehaus-parent/4/codehaus-parent-4.pom
fetch org/codehaus/codehaus-parent/4/codehaus-parent-4.pom.sha1
fetch org/codehaus/mojo/appassembler/appassembler/1.3/appassembler-1.3.pom
fetch org/codehaus/mojo/appassembler/appassembler/1.3/appassembler-1.3.pom.sha1
fetch org/codehaus/mojo/appassembler/appassembler-model/1.3/appassembler-model-1.3.jar
fetch org/codehaus/mojo/appassembler/appassembler-model/1.3/appassembler-model-1.3.jar.sha1
fetch org/codehaus/mojo/appassembler/appassembler-model/1.3/appassembler-model-1.3.pom
fetch org/codehaus/mojo/appassembler/appassembler-model/1.3/appassembler-model-1.3.pom.sha1
fetch org/codehaus/mojo/appassembler-maven-plugin/1.3/appassembler-maven-plugin-1.3.jar
fetch org/codehaus/mojo/appassembler-maven-plugin/1.3/appassembler-maven-plugin-1.3.jar.sha1
fetch org/codehaus/mojo/appassembler-maven-plugin/1.3/appassembler-maven-plugin-1.3.pom
fetch org/codehaus/mojo/appassembler-maven-plugin/1.3/appassembler-maven-plugin-1.3.pom.sha1
fetch org/codehaus/mojo/mojo-parent/30/mojo-parent-30.pom
fetch org/codehaus/mojo/mojo-parent/30/mojo-parent-30.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom
fetch org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom
fetch org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.12/plexus-1.0.12.pom
fetch org/codehaus/plexus/plexus/1.0.12/plexus-1.0.12.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom
fetch org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.5/plexus-1.0.5.pom
fetch org/codehaus/plexus/plexus/1.0.5/plexus-1.0.5.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom
fetch org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom.sha1
fetch org/codehaus/plexus/plexus/1.0.9/plexus-1.0.9.pom
fetch org/codehaus/plexus/plexus/1.0.9/plexus-1.0.9.pom.sha1
fetch org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom
fetch org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom.sha1
fetch org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom
fetch org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom.sha1
fetch org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom
fetch org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom.sha1
fetch org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom
fetch org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom.sha1
fetch org/codehaus/plexus/plexus/3.0.1/plexus-3.0.1.pom
fetch org/codehaus/plexus/plexus/3.0.1/plexus-3.0.1.pom.sha1
fetch org/codehaus/plexus/plexus/3.1/plexus-3.1.pom
fetch org/codehaus/plexus/plexus/3.1/plexus-3.1.pom.sha1
fetch org/codehaus/plexus/plexus/3.2/plexus-3.2.pom
fetch org/codehaus/plexus/plexus/3.2/plexus-3.2.pom.sha1
fetch org/codehaus/plexus/plexus/3.3.1/plexus-3.3.1.pom
fetch org/codehaus/plexus/plexus/3.3.1/plexus-3.3.1.pom.sha1
fetch org/codehaus/plexus/plexus/3.3/plexus-3.3.pom
fetch org/codehaus/plexus/plexus/3.3/plexus-3.3.pom.sha1
fetch org/codehaus/plexus/plexus-active-collections/1.0-beta-2/plexus-active-collections-1.0-beta-2.jar
fetch org/codehaus/plexus/plexus-active-collections/1.0-beta-2/plexus-active-collections-1.0-beta-2.jar.sha1
fetch org/codehaus/plexus/plexus-active-collections/1.0-beta-2/plexus-active-collections-1.0-beta-2.pom
fetch org/codehaus/plexus/plexus-active-collections/1.0-beta-2/plexus-active-collections-1.0-beta-2.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-11/plexus-archiver-1.0-alpha-11.pom
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-11/plexus-archiver-1.0-alpha-11.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-12/plexus-archiver-1.0-alpha-12.jar
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-12/plexus-archiver-1.0-alpha-12.jar.sha1
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-12/plexus-archiver-1.0-alpha-12.pom
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-12/plexus-archiver-1.0-alpha-12.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.pom
fetch org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar
fetch org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar.sha1
fetch org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.pom
fetch org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.pom
fetch org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.jar
fetch org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.jar.sha1
fetch org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.pom
fetch org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.pom.sha1
fetch org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.jar
fetch org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.jar.sha1
fetch org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.pom
fetch org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.pom.sha1
fetch org/codehaus/plexus/plexus-classworlds/1.2-alpha-6/plexus-classworlds-1.2-alpha-6.pom
fetch org/codehaus/plexus/plexus-classworlds/1.2-alpha-6/plexus-classworlds-1.2-alpha-6.pom.sha1
fetch org/codehaus/plexus/plexus-classworlds/1.2-alpha-7/plexus-classworlds-1.2-alpha-7.pom
fetch org/codehaus/plexus/plexus-classworlds/1.2-alpha-7/plexus-classworlds-1.2-alpha-7.pom.sha1
fetch org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.pom
fetch org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.pom.sha1
fetch org/codehaus/plexus/plexus-classworlds/2.2.2/plexus-classworlds-2.2.2.pom
fetch org/codehaus/plexus/plexus-classworlds/2.2.2/plexus-classworlds-2.2.2.pom.sha1
fetch org/codehaus/plexus/plexus-compiler/2.2/plexus-compiler-2.2.pom
fetch org/codehaus/plexus/plexus-compiler/2.2/plexus-compiler-2.2.pom.sha1
fetch org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.jar
fetch org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.jar.sha1
fetch org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.pom
fetch org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.pom.sha1
fetch org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.jar
fetch org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.jar.sha1
fetch org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.pom
fetch org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.pom.sha1
fetch org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.jar
fetch org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.jar.sha1
fetch org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.pom
fetch org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.pom.sha1
fetch org/codehaus/plexus/plexus-compilers/2.2/plexus-compilers-2.2.pom
fetch org/codehaus/plexus/plexus-compilers/2.2/plexus-compilers-2.2.pom.sha1
fetch org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
fetch org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar.sha1
fetch org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.pom
fetch org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.pom.sha1
fetch org/codehaus/plexus/plexus-component-api/1.0-alpha-15/plexus-component-api-1.0-alpha-15.pom
fetch org/codehaus/plexus/plexus-component-api/1.0-alpha-15/plexus-component-api-1.0-alpha-15.pom.sha1
fetch org/codehaus/plexus/plexus-component-api/1.0-alpha-16/plexus-component-api-1.0-alpha-16.pom
fetch org/codehaus/plexus/plexus-component-api/1.0-alpha-16/plexus-component-api-1.0-alpha-16.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.12/plexus-components-1.1.12.pom
fetch org/codehaus/plexus/plexus-components/1.1.12/plexus-components-1.1.12.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom
fetch org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom
fetch org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom
fetch org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.20/plexus-components-1.1.20.pom
fetch org/codehaus/plexus/plexus-components/1.1.20/plexus-components-1.1.20.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.6/plexus-components-1.1.6.pom
fetch org/codehaus/plexus/plexus-components/1.1.6/plexus-components-1.1.6.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.1.9/plexus-components-1.1.9.pom
fetch org/codehaus/plexus/plexus-components/1.1.9/plexus-components-1.1.9.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom
fetch org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom
fetch org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom.sha1
fetch org/codehaus/plexus/plexus-components/1.3/plexus-components-1.3.pom
fetch org/codehaus/plexus/plexus-components/1.3/plexus-components-1.3.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-15/plexus-container-default-1.0-alpha-15.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-15/plexus-container-default-1.0-alpha-15.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-20/plexus-container-default-1.0-alpha-20.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-20/plexus-container-default-1.0-alpha-20.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-22/plexus-container-default-1.0-alpha-22.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-22/plexus-container-default-1.0-alpha-22.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.pom
fetch org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.pom.sha1
fetch org/codehaus/plexus/plexus-container-default/1.5.5/plexus-container-default-1.5.5.pom
fetch org/codehaus/plexus/plexus-container-default/1.5.5/plexus-container-default-1.5.5.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.pom
fetch org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-15/plexus-containers-1.0-alpha-15.pom
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-15/plexus-containers-1.0-alpha-15.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-16/plexus-containers-1.0-alpha-16.pom
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-16/plexus-containers-1.0-alpha-16.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-20/plexus-containers-1.0-alpha-20.pom
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-20/plexus-containers-1.0-alpha-20.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-22/plexus-containers-1.0-alpha-22.pom
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-22/plexus-containers-1.0-alpha-22.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-30/plexus-containers-1.0-alpha-30.pom
fetch org/codehaus/plexus/plexus-containers/1.0-alpha-30/plexus-containers-1.0-alpha-30.pom.sha1
fetch org/codehaus/plexus/plexus-containers/1.5.5/plexus-containers-1.5.5.pom
fetch org/codehaus/plexus/plexus-containers/1.5.5/plexus-containers-1.5.5.pom.sha1
fetch org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
fetch org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar.sha1
fetch org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.pom
fetch org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.pom.sha1
fetch org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
fetch org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar.sha1
fetch org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.pom
fetch org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
fetch org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom
fetch org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom
fetch org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
fetch org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.pom
fetch org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.jar
fetch org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.jar.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.pom
fetch org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar
fetch org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.pom
fetch org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.6/plexus-interpolation-1.6.pom
fetch org/codehaus/plexus/plexus-interpolation/1.6/plexus-interpolation-1.6.pom.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.7/plexus-interpolation-1.7.jar
fetch org/codehaus/plexus/plexus-interpolation/1.7/plexus-interpolation-1.7.jar.sha1
fetch org/codehaus/plexus/plexus-interpolation/1.7/plexus-interpolation-1.7.pom
fetch org/codehaus/plexus/plexus-interpolation/1.7/plexus-interpolation-1.7.pom.sha1
fetch org/codehaus/plexus/plexus-io/1.0-alpha-3/plexus-io-1.0-alpha-3.pom
fetch org/codehaus/plexus/plexus-io/1.0-alpha-3/plexus-io-1.0-alpha-3.pom.sha1
fetch org/codehaus/plexus/plexus-io/1.0-alpha-4/plexus-io-1.0-alpha-4.jar
fetch org/codehaus/plexus/plexus-io/1.0-alpha-4/plexus-io-1.0-alpha-4.jar.sha1
fetch org/codehaus/plexus/plexus-io/1.0-alpha-4/plexus-io-1.0-alpha-4.pom
fetch org/codehaus/plexus/plexus-io/1.0-alpha-4/plexus-io-1.0-alpha-4.pom.sha1
fetch org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.jar
fetch org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.jar.sha1
fetch org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.pom
fetch org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.pom.sha1
fetch org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.pom
fetch org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.pom.sha1
fetch org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
fetch org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar.sha1
fetch org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.pom
fetch org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom
fetch org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.pom
fetch org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.2/plexus-utils-1.2.pom
fetch org/codehaus/plexus/plexus-utils/1.2/plexus-utils-1.2.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.3/plexus-utils-1.3.pom
fetch org/codehaus/plexus/plexus-utils/1.3/plexus-utils-1.3.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.pom
fetch org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.4.2/plexus-utils-1.4.2.pom
fetch org/codehaus/plexus/plexus-utils/1.4.2/plexus-utils-1.4.2.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.4.5/plexus-utils-1.4.5.pom
fetch org/codehaus/plexus/plexus-utils/1.4.5/plexus-utils-1.4.5.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.4.6/plexus-utils-1.4.6.pom
fetch org/codehaus/plexus/plexus-utils/1.4.6/plexus-utils-1.4.6.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.pom
fetch org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.pom
fetch org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar
fetch org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.pom
fetch org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.pom
fetch org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar
fetch org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.pom
fetch org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.7/plexus-utils-1.5.7.pom
fetch org/codehaus/plexus/plexus-utils/1.5.7/plexus-utils-1.5.7.pom.sha1
fetch org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.pom
fetch org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.pom.sha1
fetch org/codehaus/plexus/plexus-utils/2.0.1/plexus-utils-2.0.1.jar
fetch org/codehaus/plexus/plexus-utils/2.0.1/plexus-utils-2.0.1.jar.sha1
fetch org/codehaus/plexus/plexus-utils/2.0.1/plexus-utils-2.0.1.pom
fetch org/codehaus/plexus/plexus-utils/2.0.1/plexus-utils-2.0.1.pom.sha1
fetch org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
fetch org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar.sha1
fetch org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom
fetch org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.jar
fetch org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.jar.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.pom
fetch org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.pom.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.2/plexus-utils-3.0.2.pom
fetch org/codehaus/plexus/plexus-utils/3.0.2/plexus-utils-3.0.2.pom.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar
fetch org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom
fetch org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.7/plexus-utils-3.0.7.pom
fetch org/codehaus/plexus/plexus-utils/3.0.7/plexus-utils-3.0.7.pom.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
fetch org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar.sha1
fetch org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom
fetch org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom.sha1
fetch org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom
fetch org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom.sha1
fetch org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
fetch org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar.sha1
fetch org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.pom
fetch org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.pom.sha1
fetch org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom
fetch org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom.sha1
fetch org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
fetch org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar.sha1
fetch org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
fetch org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom.sha1
fetch org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1.pom
fetch org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1.pom.sha1
fetch org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
fetch org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom.sha1
fetch org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
fetch org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar.sha1
fetch org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom
fetch org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom.sha1
fetch org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.jar
fetch org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.jar.sha1
fetch org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.pom
fetch org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.pom.sha1
fetch org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom
fetch org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom.sha1
fetch org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
fetch org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar.sha1
fetch org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom
fetch org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom.sha1
fetch org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar
fetch org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar.sha1
fetch org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom
fetch org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom.sha1
fetch org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
fetch org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar.sha1
fetch org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom
fetch org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom.sha1
fetch org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar
fetch org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar.sha1
fetch org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.pom
fetch org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.pom.sha1
fetch org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom
fetch org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom.sha1
fetch org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom
fetch org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom.sha1
fetch org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
fetch org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom.sha1
fetch org/sonatype/forge/forge-parent/10/forge-parent-10.pom
fetch org/sonatype/forge/forge-parent/10/forge-parent-10.pom.sha1
fetch org/sonatype/forge/forge-parent/3/forge-parent-3.pom
fetch org/sonatype/forge/forge-parent/3/forge-parent-3.pom.sha1
fetch org/sonatype/forge/forge-parent/4/forge-parent-4.pom
fetch org/sonatype/forge/forge-parent/4/forge-parent-4.pom.sha1
fetch org/sonatype/forge/forge-parent/5/forge-parent-5.pom
fetch org/sonatype/forge/forge-parent/5/forge-parent-5.pom.sha1
fetch org/sonatype/oss/oss-parent/7/oss-parent-7.pom
fetch org/sonatype/oss/oss-parent/7/oss-parent-7.pom.sha1
fetch org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar
fetch org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar.sha1
fetch org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom
fetch org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom.sha1
fetch org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
fetch org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar.sha1
fetch org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.pom
fetch org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.pom.sha1
fetch org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
fetch org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar.sha1
fetch org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.pom
fetch org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.pom.sha1
fetch org/sonatype/spice/spice-parent/10/spice-parent-10.pom
fetch org/sonatype/spice/spice-parent/10/spice-parent-10.pom.sha1
fetch org/sonatype/spice/spice-parent/12/spice-parent-12.pom
fetch org/sonatype/spice/spice-parent/12/spice-parent-12.pom.sha1
fetch org/sonatype/spice/spice-parent/16/spice-parent-16.pom
fetch org/sonatype/spice/spice-parent/16/spice-parent-16.pom.sha1
fetch org/sonatype/spice/spice-parent/17/spice-parent-17.pom
fetch org/sonatype/spice/spice-parent/17/spice-parent-17.pom.sha1
fetch org/tukaani/xz/1.2/xz-1.2.jar
fetch org/tukaani/xz/1.2/xz-1.2.jar.sha1
fetch org/tukaani/xz/1.2/xz-1.2.pom
fetch org/tukaani/xz/1.2/xz-1.2.pom.sha1
fetch oro/oro/2.0.8/oro-2.0.8.jar
fetch oro/oro/2.0.8/oro-2.0.8.jar.sha1
fetch oro/oro/2.0.8/oro-2.0.8.pom
fetch oro/oro/2.0.8/oro-2.0.8.pom.sha1
fetch stax/stax/1.1.1-dev/stax-1.1.1-dev.jar
fetch stax/stax/1.1.1-dev/stax-1.1.1-dev.jar.sha1
fetch stax/stax/1.1.1-dev/stax-1.1.1-dev.pom
fetch stax/stax/1.1.1-dev/stax-1.1.1-dev.pom.sha1
fetch stax/stax-api/1.0.1/stax-api-1.0.1.jar
fetch stax/stax-api/1.0.1/stax-api-1.0.1.jar.sha1
fetch stax/stax-api/1.0.1/stax-api-1.0.1.pom
fetch stax/stax-api/1.0.1/stax-api-1.0.1.pom.sha1
fetch xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar
fetch xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar.sha1
fetch xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.pom
fetch xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.pom.sha1
fetch xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
fetch xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar.sha1
fetch xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.pom
fetch xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.pom.sha1
